services:
  banco:
    image: postgres:17
    container_name: banco-dados
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sl_imobiliaria
    ports:
      - "5432:5432"

volumes:
  postgres_data: